# Generated by Django 3.2.5 on 2021-08-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptocurrency', '0013_auto_20210802_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrency.cryptocurrency')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoAccount.owned')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptoAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
