# Generated by Django 3.2 on 2021-10-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptoAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cryptoAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CryptoAccountDTO',
        ),
        migrations.AddField(
            model_name='owned',
            name='account',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='cryptoAccount.cryptoaccount'),
        ),
    ]
