# Generated by Django 3.2.5 on 2021-08-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoaccount',
            name='owned',
        ),
        migrations.AddField(
            model_name='owned',
            name='account',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned', to='cryptoAccount.cryptoaccount'),
        ),
    ]
