# Generated by Django 3.2.5 on 2021-07-30 16:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 16, 32, 0, 911494)),
        ),
    ]
