# Generated by Django 3.2.5 on 2021-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cryptocurrency', '0002_auto_20210728_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
