# Generated by Django 3.2.5 on 2021-08-02 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cryptocurrency', '0003_auto_20210728_2117'),
        ('cryptocurrency', '0011_alter_price_date'),
    ]

    operations = [
    ]
